# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('favorite_topics', multiselectfield.db.fields.MultiSelectField(choices=[('Sports', 'Sports'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Odd News', 'Odd News'), ('Local', 'Local'), ('International', 'International'), ('Music', 'Music'), ('Trending', 'Trending'), ('Technology', 'Technology'), ('Science', 'Science'), ('Business', 'Business'), ('Finance', 'Finance'), ('Television', 'Television'), ('Movies', 'Movies'), ('Celebrities', 'Celebrities'), ('Social Media', 'Social Media'), ('Food', 'Food'), ('Health', 'Health'), ('Nature', 'Nature'), ('Kids', 'Kids'), ('Breaking News', 'Breaking News'), ('Travel', 'Travel'), ('Substances', 'Substances'), ('United States', 'United States'), ('Animals', 'Animals'), ('Art', 'Art'), ('Education', 'Education'), ('Employment', 'Employment'), ('Brands', 'Brands')], default=('Odd News', 'Odd News'), max_length=270)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
